name: Build and Deploy to K8S

on:
  push:
    branches: [main]

env:
  IMAGE_TAG: ${{ github.sha }}
  ECR_REPOSITORY: mcp-server
  DEPLOYMENT_NAME: mcp-server

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/deployer
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: Dockerfile
          tags: |
            "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
            "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest"

      - name: Install kubectl and update kubeconfig
        run: |
          curl -sSL -o kubectl https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          aws eks --region us-east-1 update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }}

      - name: Deploy to k8s
        env:
          DEPLOYMENT_NAME: ${{ env.DEPLOYMENT_NAME }}
          K8S_NAMESPACE: ${{ vars.K8S_NAMESPACE }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          MCP_API_KEY: ${{ secrets.MCP_API_KEY }}
          KEYCLOAK_API_HOST: ${{ vars.KEYCLOAK_API_HOST }}
          KEYCLOAK_CLIENT_ID: ${{ secrets.KEYCLOAK_CLIENT_ID }}
          KEYCLOAK_CLIENT_SECRET: ${{ secrets.KEYCLOAK_CLIENT_SECRET }}
          IA_API_HOST: ${{ vars.IA_API_HOST }}
          QDRANT_HOST: ${{ vars.QDRANT_HOST }}
          QDRANT_PORT: ${{ vars.QDRANT_PORT }}
          QDRANT_API_KEY: ${{ secrets.QDRANT_API_KEY }}
          QDRANT_COLLECTION_NAME: ${{ vars.QDRANT_COLLECTION_NAME }}
          GH_APP_ID: ${{ vars.GH_APP_ID }}
          GH_APP_INSTALLATION_ID: ${{ vars.GH_APP_INSTALLATION_ID }}
          GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
          REDIS_HOST: ${{ vars.REDIS_HOST }}
          REDIS_PORT: ${{ vars.REDIS_PORT }}
          REDIS_DB: ${{ vars.REDIS_DB }}
        run: |
          sh ./k8s/build-deployment.yaml.sh
          kubectl apply -f deployment.yaml
          kubectl rollout restart deployment/${DEPLOYMENT_NAME} -n ${K8S_NAMESPACE}

      - name: Check rollout
        run: |
          kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ vars.K8S_NAMESPACE }}
